training:
  train_data: "./Ollama/Instruction Bot/dataset/train.jsonl"
  val_data: "./Ollama/Instruction Bot/dataset/val.jsonl"
  batch_size: 2
  learning_rate: 3e-5
  epochs: 3
  save_steps: 500
  output_dir: "./Ollama/Instruction Bot/llama3-finetuned"
  device: "cpu"

# python -m unsloth train --config ./Ollama/Instruction Bot/fine-tune.yaml